name: Build and deploy Python app to Azure Web App - bastaferry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: List directory contents
        run: ls -la

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Verify Python version
        run: python --version

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          if [ -d "venv/bin" ]; then
            echo "Virtual environment created successfully."
          else
            echo "Failed to create virtual environment."
            exit 1
          fi
          . venv/bin/activate
          ls -la venv/bin

      - name: Install dependencies
        run: |
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_942121EE2D3E46E09A703AF722920B79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EACAD066AA1C47EA890C09B52F93C2C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88C525DDE08C44DF9F9B0039AA8321B1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bastaferry'
          slot-name: 'Production'
